"""migracion_inicial

Revision ID: 064dec86fdb7
Revises: 
Create Date: 2026-06-09 14:49:38.208286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064dec86fdb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_modulos_id'), 'modulos', ['id'], unique=False)
    op.create_index(op.f('ix_perfiles_id'), 'perfiles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_index(op.f('idx_sesiones_token_valido'), table_name='sesiones', postgresql_where='(valida = true)')
    op.drop_constraint(op.f('sesiones_token_sesion_hash_key'), 'sesiones', type_='unique')
    op.create_index(op.f('ix_sesiones_id'), 'sesiones', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_token_sesion_hash'), 'sesiones', ['token_sesion_hash'], unique=True)
    op.drop_index(op.f('idx_usuarios_email_activo'), table_name='usuarios', postgresql_where="((estado)::text = 'ACTIVO'::text)")
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_usuarios_email_activo'), 'usuarios', ['email'], unique=False, postgresql_where="((estado)::text = 'ACTIVO'::text)")
    op.drop_index(op.f('ix_sesiones_token_sesion_hash'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_id'), table_name='sesiones')
    op.create_unique_constraint(op.f('sesiones_token_sesion_hash_key'), 'sesiones', ['token_sesion_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sesiones_token_valido'), 'sesiones', ['token_sesion_hash'], unique=False, postgresql_where='(valida = true)')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_perfiles_id'), table_name='perfiles')
    op.drop_index(op.f('ix_modulos_id'), table_name='modulos')
    # ### end Alembic commands ###
