"""add_audit_columns_to_historial_importacion

Revision ID: 2ed9f8bcd71f
Revises: 8cf6662d2765
Create Date: 2026-07-16 16:09:01.943893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed9f8bcd71f'
down_revision: Union[str, Sequence[str], None] = '8cf6662d2765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_importaciones', sa.Column('clientes_nuevos', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('clientes_actualizados', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('cargos_nuevos', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('cargos_actualizados', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('telefonos_nuevos', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('telefono_uso_actualizados', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('movimientos_financieros_creados', sa.Integer(), server_default='0', nullable=False))
    op.add_column('historial_importaciones', sa.Column('monto_deuda_inicial_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.add_column('historial_importaciones', sa.Column('monto_interes_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.add_column('historial_importaciones', sa.Column('monto_gasto_adm_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.add_column('historial_importaciones', sa.Column('duracion_segundos', sa.Numeric(precision=8, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historial_importaciones', 'duracion_segundos')
    op.drop_column('historial_importaciones', 'monto_gasto_adm_total')
    op.drop_column('historial_importaciones', 'monto_interes_total')
    op.drop_column('historial_importaciones', 'monto_deuda_inicial_total')
    op.drop_column('historial_importaciones', 'movimientos_financieros_creados')
    op.drop_column('historial_importaciones', 'telefono_uso_actualizados')
    op.drop_column('historial_importaciones', 'telefonos_nuevos')
    op.drop_column('historial_importaciones', 'cargos_actualizados')
    op.drop_column('historial_importaciones', 'cargos_nuevos')
    op.drop_column('historial_importaciones', 'clientes_actualizados')
    op.drop_column('historial_importaciones', 'clientes_nuevos')
    # ### end Alembic commands ###
