"""add_historial_importacion_and_update_cargo_constraint

Revision ID: 690b5f474a49
Revises: 888fdd560e73
Create Date: 2026-07-16 11:17:03.851809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690b5f474a49'
down_revision: Union[str, Sequence[str], None] = '888fdd560e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_importaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('hash_archivo', sa.String(length=64), nullable=False),
    sa.Column('tipo_subida', sa.String(length=50), nullable=False),
    sa.Column('fecha_importacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('registros_procesados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tramo_id'], ['tramos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_importaciones_hash_archivo'), 'historial_importaciones', ['hash_archivo'], unique=True)
    op.create_index(op.f('ix_historial_importaciones_id'), 'historial_importaciones', ['id'], unique=False)
    op.drop_constraint(op.f('uq_cliente_cargo_tramo'), 'cargos', type_='unique')
    op.create_unique_constraint('uq_cliente_cargo_tramo_campana', 'cargos', ['cliente_id', 'numero_cargo', 'tramo_id', 'campana_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cliente_cargo_tramo_campana', 'cargos', type_='unique')
    op.create_unique_constraint(op.f('uq_cliente_cargo_tramo'), 'cargos', ['cliente_id', 'numero_cargo', 'tramo_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_historial_importaciones_id'), table_name='historial_importaciones')
    op.drop_index(op.f('ix_historial_importaciones_hash_archivo'), table_name='historial_importaciones')
    op.drop_table('historial_importaciones')
    # ### end Alembic commands ###
