"""crear_tablas_configuracion_tramos

Revision ID: 888fdd560e73
Revises: 064dec86fdb7
Create Date: 2026-07-10 12:10:03.066379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888fdd560e73'
down_revision: Union[str, Sequence[str], None] = '064dec86fdb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_campanas_id'), 'campanas', ['id'], unique=False)
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.create_table('perfiles_riesgo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_perfiles_riesgo_id'), 'perfiles_riesgo', ['id'], unique=False)
    op.create_table('segmentos_rolling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_segmentos_rolling_id'), 'segmentos_rolling', ['id'], unique=False)
    op.create_table('tramos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tramos_id'), 'tramos', ['id'], unique=False)
    op.create_table('configuracion_prioridad_telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_columna_excel', sa.String(length=100), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tramo_id'], ['tramos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tramo_id', 'nombre_columna_excel', name='uq_tramo_telefono_excel')
    )
    op.create_index(op.f('ix_configuracion_prioridad_telefonos_id'), 'configuracion_prioridad_telefonos', ['id'], unique=False)
    op.create_table('mapeo_columnas_tramo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_campo', sa.String(length=20), nullable=False),
    sa.Column('campo_sistema', sa.String(length=50), nullable=False),
    sa.Column('nombre_columna_excel', sa.String(length=100), nullable=False),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tramo_id'], ['tramos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tramo_id', 'campo_sistema', name='uq_tramo_campo_sistema'),
    sa.UniqueConstraint('tramo_id', 'nombre_columna_excel', name='uq_tramo_columna_excel')
    )
    op.create_index(op.f('ix_mapeo_columnas_tramo_id'), 'mapeo_columnas_tramo', ['id'], unique=False)
    op.create_table('plantillas_mapeo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tramo_id'], ['tramos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tramo_id', 'nombre', name='uq_tramo_nombre_plantilla')
    )
    op.create_index(op.f('ix_plantillas_mapeo_id'), 'plantillas_mapeo', ['id'], unique=False)
    op.create_table('secciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secciones_id'), 'secciones', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_cliente_belcor', sa.String(length=100), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('perfil_riesgo_id', sa.Integer(), nullable=True),
    sa.Column('segmento_rolling_id', sa.Integer(), nullable=True),
    sa.Column('telefono_uso', sa.String(length=20), nullable=True),
    sa.Column('observacion_telefono', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perfil_riesgo_id'], ['perfiles_riesgo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['segmento_rolling_id'], ['segmentos_rolling.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_codigo_cliente_belcor'), 'clientes', ['codigo_cliente_belcor'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('plantillas_columnas',
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('columna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['columna_id'], ['mapeo_columnas_tramo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_mapeo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plantilla_id', 'columna_id')
    )
    op.create_table('plantillas_telefonos',
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('telefono_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_mapeo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telefono_id'], ['configuracion_prioridad_telefonos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plantilla_id', 'telefono_id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_cargo', sa.String(length=100), nullable=False),
    sa.Column('tramo_id', sa.Integer(), nullable=False),
    sa.Column('campana_id', sa.Integer(), nullable=False),
    sa.Column('dias_atraso', sa.Integer(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_interes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_gasto_adm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_descontar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deuda_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_cobrar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tramo_id'], ['tramos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'numero_cargo', 'tramo_id', name='uq_cliente_cargo_tramo')
    )
    op.create_index(op.f('ix_cargos_id'), 'cargos', ['id'], unique=False)
    op.create_table('telefonos_clientes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('prioridad', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo_cambio', sa.String(length=255), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefonos_clientes_id'), 'telefonos_clientes', ['id'], unique=False)
    op.create_table('movimientos_cargos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cargo_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=30), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_cargos_id'), 'movimientos_cargos', ['id'], unique=False)
    
    # Crear la función trigger
    op.execute("""
    CREATE OR REPLACE FUNCTION fn_actualizar_saldos_cargo()
    RETURNS TRIGGER AS $$
    DECLARE
        target_cargo_id BIGINT;
    BEGIN
        IF TG_OP = 'DELETE' THEN
            target_cargo_id := OLD.cargo_id;
        ELSE
            target_cargo_id := NEW.cargo_id;
        END IF;

        UPDATE cargos
        SET 
            monto_inicial = COALESCE((SELECT SUM(monto) FROM movimientos_cargos WHERE cargo_id = target_cargo_id AND tipo_movimiento = 'INICIAL'), 0.00),
            monto_interes = COALESCE((SELECT SUM(monto) FROM movimientos_cargos WHERE cargo_id = target_cargo_id AND tipo_movimiento = 'INTERES'), 0.00),
            monto_gasto_adm = COALESCE((SELECT SUM(monto) FROM movimientos_cargos WHERE cargo_id = target_cargo_id AND tipo_movimiento = 'GASTO_ADM'), 0.00),
            monto_pagado = COALESCE((SELECT SUM(monto) FROM movimientos_cargos WHERE cargo_id = target_cargo_id AND tipo_movimiento = 'PAGO'), 0.00),
            monto_descontar = COALESCE((SELECT SUM(monto) FROM movimientos_cargos WHERE cargo_id = target_cargo_id AND tipo_movimiento = 'DESCUENTO'), 0.00)
        WHERE id = target_cargo_id;
        
        UPDATE cargos
        SET
            deuda_total = monto_inicial + monto_interes + monto_gasto_adm,
            saldo_cobrar = (monto_inicial + monto_interes + monto_gasto_adm) - monto_pagado - monto_descontar
        WHERE id = target_cargo_id;

        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # Crear el trigger físico
    op.execute("""
    CREATE TRIGGER trg_actualizar_saldos_cargo
    AFTER INSERT OR UPDATE OR DELETE ON movimientos_cargos
    FOR EACH ROW
    EXECUTE FUNCTION fn_actualizar_saldos_cargo();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Droppear el trigger y la función
    op.execute("DROP TRIGGER IF EXISTS trg_actualizar_saldos_cargo ON movimientos_cargos;")
    op.execute("DROP FUNCTION IF EXISTS fn_actualizar_saldos_cargo();")
    op.drop_index(op.f('ix_movimientos_cargos_id'), table_name='movimientos_cargos')
    op.drop_table('movimientos_cargos')
    op.drop_index(op.f('ix_telefonos_clientes_id'), table_name='telefonos_clientes')
    op.drop_table('telefonos_clientes')
    op.drop_index(op.f('ix_cargos_id'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_table('plantillas_telefonos')
    op.drop_table('plantillas_columnas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_codigo_cliente_belcor'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_secciones_id'), table_name='secciones')
    op.drop_table('secciones')
    op.drop_index(op.f('ix_plantillas_mapeo_id'), table_name='plantillas_mapeo')
    op.drop_table('plantillas_mapeo')
    op.drop_index(op.f('ix_mapeo_columnas_tramo_id'), table_name='mapeo_columnas_tramo')
    op.drop_table('mapeo_columnas_tramo')
    op.drop_index(op.f('ix_configuracion_prioridad_telefonos_id'), table_name='configuracion_prioridad_telefonos')
    op.drop_table('configuracion_prioridad_telefonos')
    op.drop_index(op.f('ix_tramos_id'), table_name='tramos')
    op.drop_table('tramos')
    op.drop_index(op.f('ix_segmentos_rolling_id'), table_name='segmentos_rolling')
    op.drop_table('segmentos_rolling')
    op.drop_index(op.f('ix_perfiles_riesgo_id'), table_name='perfiles_riesgo')
    op.drop_table('perfiles_riesgo')
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_campanas_id'), table_name='campanas')
    op.drop_table('campanas')
    # ### end Alembic commands ###
