"""add_tipo_proceso_to_plantilla_mapeo

Revision ID: 8cf6662d2765
Revises: 690b5f474a49
Create Date: 2026-07-16 12:33:13.106077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf6662d2765'
down_revision: Union[str, Sequence[str], None] = '690b5f474a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Añadir la columna como nullable primero
    op.add_column('plantillas_mapeo', sa.Column('tipo_proceso', sa.String(length=50), nullable=True))
    
    # 2. Poblar los registros existentes con el valor por defecto
    op.execute("UPDATE plantillas_mapeo SET tipo_proceso = 'BASE_ORIGINAL'")
    
    # 3. Alterar la columna para que sea NOT NULL
    op.alter_column('plantillas_mapeo', 'tipo_proceso', nullable=False)
    
    # 4. Crear el constraint CHECK
    op.create_check_constraint(
        'chk_tipo_proceso',
        'plantillas_mapeo',
        sa.text("tipo_proceso IN ('BASE_ORIGINAL', 'BASE_ACTUALIZACION', 'BASE_SALDOS')")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantillas_mapeo', 'tipo_proceso')
    # ### end Alembic commands ###
