"""agregar_descuento_config

Revision ID: 9443526073ad
Revises: 2ed9f8bcd71f
Create Date: 2026-07-21 12:40:47.195863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9443526073ad'
down_revision: Union[str, Sequence[str], None] = '2ed9f8bcd71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descuentos_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descuento_monto_fijo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pct_descuento_capital', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pct_descuento_interes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pct_descuento_gasto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('campanas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('departamentos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('perfiles_riesgo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segmentos_rolling', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tramo_id'], ['tramos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descuentos_config_id'), 'descuentos_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_descuentos_config_id'), table_name='descuentos_config')
    op.drop_table('descuentos_config')
    # ### end Alembic commands ###
